### ISSUE TITLE
Framework Detection Dialog: Irritating. Spurious? Useless?

### ISSUE THREAD

**Issue by chgraham** [robovm/robovm-studio#13]
Previously, I installed Android SDKs and components for the build tools, as well as Android platforms using the SDK manager via Android Studio.

Now, create a new cross-platform project in RVM Studio 1.5.0.

Popup appears:
  Frameworks detected
  Android framework is detected in the project Configure

Now, I click the Configure link, and a popup appears:
  Framework detection
  No frameworks are detected

**Comment by badlogic** [comment]
This has been fixed in IntelliJ IDEA 15 as well as the latest RoboVM Studio.
