### ISSUE TITLE
RoboVM Studio does not detect Xcode.

### ISSUE THREAD

**Issue by svanimpe** [robovm/robovm-studio#18]
I cannot get past the following screen:
<img width="697" alt="screen shot 2015-10-06 at 09 05 25" src="https://cloud.githubusercontent.com/assets/1496250/10302103/717bc212-6c09-11e5-9fc5-38ae75b586d7.png">

I have Xcode 7.0.1 installed (and use it regularly), including the command-line tools.

**Comment by badlogic** [comment]
What directory did you install Xcode in? What does `xcode-select -p` print
on the terminal?

**Comment by svanimpe** [comment]
Aha, `xcode-select -p` said it was still set to Xcode-beta (which I no longer have installed). I used `xcode-select -s` to change it to my currently installed version. This fixed it, thanks!

**Comment by badlogic** [comment]
Great! Closing this out then.
